# Generated by Django 4.1.3 on 2022-11-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_birthday_remove_user_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
