# Generated by Django 4.1.3 on 2022-12-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_critique_ticket_alter_critique_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='starred',
        ),
    ]
