# Generated by Django 4.1.3 on 2022-12-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticket_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.AlterField(
            model_name='critique',
            name='comment',
            field=models.TextField(max_length=5000, verbose_name='Votre'),
        ),
        migrations.AlterField(
            model_name='critique',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Titre de la critique'),
        ),
    ]
