# Generated by Django 4.1.3 on 2022-12-12 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_critique_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critique',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='critique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.critique'),
        ),
    ]
