# Generated by Django 4.1.3 on 2022-12-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_remove_critique_ticket_ticket_critique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='critique',
        ),
        migrations.AddField(
            model_name='critique',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ticket'),
        ),
    ]
