# Generated by Django 4.1.3 on 2022-12-13 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_critique_author_alter_critique_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critique',
            name='ticket',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket'),
            preserve_default=False,
        ),
    ]
