# Generated by Django 4.1.3 on 2022-12-13 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0016_alter_critique_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critique',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='critique',
            name='comment',
            field=models.TextField(max_length=5000, verbose_name='Votre commentaire'),
        ),
    ]
