# Generated by Django 4.1.3 on 2022-12-21 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_alter_critique_author_alter_critique_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='critique',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='critique',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')]),
        ),
    ]
