# Generated by Django 4.1.3 on 2022-12-22 05:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0020_critique_date_created_alter_critique_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Critique',
            new_name='Review',
        ),
    ]
