# Generated by Django 4.1.3 on 2022-12-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_rename_critique_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='review_title',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='ticket_title',
        ),
    ]
