# Generated by Django 4.1.3 on 2023-01-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.photo'),
        ),
    ]
